version: '3.9'

services:
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  tunnel:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest 
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TOKEN}
    depends_on: 
      - web
networks:
  default:
    name: web
  
